# Generated by Django 4.2 on 2026-03-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facture", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blmoto",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="facturemoto",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="factureoperation",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
