# Generated by Django 3.1.6 on 2021-02-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exportateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=500)),
                ('adresse', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('NIF', models.CharField(max_length=500)),
                ('NIF_PJ', models.FileField(blank=True, upload_to='images')),
                ('STAT', models.CharField(max_length=500)),
                ('STAT_PJ', models.FileField(blank=True, upload_to='images')),
                ('RCS', models.CharField(max_length=500)),
                ('RCS_PJ', models.FileField(blank=True, upload_to='images')),
                ('ID_BSC', models.CharField(max_length=500)),
                ('login', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=500)),
                ('banque', models.CharField(max_length=500)),
                ('numCompte', models.CharField(max_length=500)),
                ('CIN_gerant', models.IntegerField(null=True)),
                ('CIN_PJ', models.FileField(blank=True, upload_to='images')),
                ('cachet', models.FileField(blank=True, upload_to='images')),
                ('numTel', models.CharField(max_length=500)),
            ],
        ),
    ]
