# Generated by Django 3.1.7 on 2022-02-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moto',
            name='carte_grise',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
