# Generated by Django 3.1.7 on 2022-05-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moto', '0002_moto_carte_grise'),
    ]

    operations = [
        migrations.AddField(
            model_name='moto',
            name='magasin',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
