# Generated by Django 3.2 on 2022-07-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moto', '0003_moto_magasin'),
    ]

    operations = [
        migrations.AddField(
            model_name='moto',
            name='date_BL',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='moto',
            name='date_facture',
            field=models.DateField(null=True),
        ),
    ]
