# Generated by Django 3.2 on 2022-07-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moto', '0004_auto_20220704_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='moto',
            name='date_arrivee',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='moto',
            name='localisation',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
