# Generated by Django 3.2 on 2022-08-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moto', '0006_moto_vendeur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moto',
            name='num_moteur',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
