# Generated by Django 3.2 on 2022-08-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moto', '0007_alter_moto_num_moteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moto',
            name='PJ_CIN_Client_1_recto',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='moto',
            name='PJ_CIN_Client_1_verso',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='moto',
            name='PJ_CIN_Client_2_recto',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='moto',
            name='PJ_CIN_Client_2_verso',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
