# Generated by Django 3.2 on 2022-08-08 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moto', '0010_alter_moto_date_facture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moto',
            name='CIN_Num_Client_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='moto',
            name='CIN_Num_Client_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='moto',
            name='adresse_client_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='moto',
            name='adresse_client_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='moto',
            name='fournisseur',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='moto',
            name='nom_client_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='moto',
            name='nom_client_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='moto',
            name='tel_client_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='moto',
            name='tel_client_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
