# Generated by Django 3.2 on 2022-08-08 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moto', '0011_auto_20220808_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moto',
            name='commercial',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
