# Generated by Django 3.2 on 2022-08-08 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moto', '0012_alter_moto_commercial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moto',
            name='ID_Moto',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
