# Generated by Django 3.2 on 2022-08-08 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moto', '0013_alter_moto_id_moto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moto',
            name='FRN',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='moto',
            name='carte_grise',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='moto',
            name='carte_rose',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='moto',
            name='date_vente',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moto',
            name='localisation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='moto',
            name='magasin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='moto',
            name='model_no_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='moto',
            name='motif_reparation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='moto',
            name='nom_moto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='moto',
            name='volume_moteur',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
