# Generated by Django 3.2 on 2022-08-08 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moto', '0014_auto_20220808_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moto',
            name='ID_Moto',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
