# Generated by Django 4.2 on 2026-03-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moto", "0015_alter_moto_id_moto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moto",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
