# Generated by Django 3.2 on 2022-08-15 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaisseMoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libellee', models.CharField(max_length=50)),
                ('date', models.DateField(null=True)),
                ('depense', models.DecimalField(decimal_places=2, default='0', max_digits=20, null=True)),
                ('recette', models.DecimalField(decimal_places=2, default='0', max_digits=20, null=True)),
                ('PJ', models.FileField(blank=True, upload_to='images')),
                ('is_depense', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Solde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soldeInitial', models.DecimalField(decimal_places=2, default='0', max_digits=20, null=True)),
                ('soldeActuel', models.DecimalField(decimal_places=2, default='0', max_digits=20, null=True)),
            ],
        ),
    ]
