# Generated by Django 3.2 on 2022-08-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisseMoto', '0002_auto_20220815_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caissemoto',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
