# Generated by Django 3.2 on 2022-08-16 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moto', '0015_alter_moto_id_moto'),
        ('caisseMoto', '0004_caissemoto_is_moto'),
    ]

    operations = [
        migrations.AddField(
            model_name='caissemoto',
            name='ID_Moto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moto.moto'),
        ),
    ]
