# Generated by Django 3.2 on 2022-08-16 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caisseMoto', '0006_rename_id_moto_caissemoto_id_moto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caissemoto',
            old_name='id_Moto',
            new_name='id_moto',
        ),
    ]
