# Generated by Django 3.2 on 2022-08-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisseMoto', '0007_rename_id_moto_caissemoto_id_moto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caissemoto',
            name='is_moto',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
