# Generated by Django 3.2 on 2022-08-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisseMoto', '0008_alter_caissemoto_is_moto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caissemoto',
            name='PJ',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
