# Generated by Django 3.2 on 2022-08-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisseMoto', '0009_alter_caissemoto_pj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caissemoto',
            name='depense',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='caissemoto',
            name='is_depense',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='caissemoto',
            name='recette',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=20, null=True),
        ),
    ]
