# Generated by Django 3.2 on 2022-08-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisseMoto', '0011_alter_caissemoto_is_moto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caissemoto',
            name='is_depense',
            field=models.BooleanField(default=False),
        ),
    ]
