# Generated by Django 2.2.13 on 2020-06-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Versement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('reference', models.CharField(max_length=500)),
                ('beneficiaire', models.CharField(max_length=500)),
                ('montant', models.IntegerField(default='0')),
                ('remarque', models.CharField(max_length=500)),
                ('PJ', models.FileField(blank=True, upload_to='images')),
            ],
        ),
    ]
