# Generated by Django 3.1.6 on 2021-02-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caisse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libellee', models.CharField(max_length=50)),
                ('date', models.DateField(null=True)),
                ('depense', models.DecimalField(decimal_places=2, default='0', max_digits=20, null=True)),
                ('recette', models.DecimalField(decimal_places=2, default='0', max_digits=20, null=True)),
                ('PJ', models.FileField(blank=True, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Solde',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soldeInitial', models.DecimalField(decimal_places=2, default='0', max_digits=20, null=True)),
                ('soldeActuel', models.DecimalField(decimal_places=2, default='0', max_digits=20, null=True)),
            ],
        ),
    ]
